[project]
name = "100-days-of-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "bootstrap-flask>=2.5.0",
    "email-validator>=2.3.0",
    "flask>=3.1.2",
    "flask-ckeditor>=1.0.0",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "flask-wtf>=1.2.2",
    "getname>=0.1.1",
    "gunicorn>=25.0.3",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "nbformat>=5.11.1",
    "pandas>=3.0.1",
    "plotly>=7.0.0",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "selenium>=4.39.0",
    "spotipy>=2.25.2",
    "werkzeug>=3.1.5",
    "wtforms>=3.2.1",
]
